import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '@/pages/home/styles.module.css';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta content='Generated by create next app' name='description' />
      <link href='/favicon.ico' rel='icon' />
    </Head>
    <main className={styles.main}>
      <h1 className={styles.title}>This changed!</h1>
    </main>
  </div>
);

export default Home;
